-- MySQL Script generated by MySQL Workbench
-- Tue Jul 12 18:18:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dfin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dfin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dfin` DEFAULT CHARACTER SET utf8 ;
USE `dfin` ;

-- -----------------------------------------------------
-- Table `dfin`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfin`.`estado` (
  `cod_estado` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `sigla_estado` VARCHAR(2) NULL,
  PRIMARY KEY (`cod_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfin`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfin`.`cliente` (
  `cod_cliente` INT NOT NULL AUTO_INCREMENT,
  `sexo` INT NULL,
  `idade` INT NULL,
  `qtd_filhos` INT NULL,
  `estado_civil` INT NULL,
  `cod_estado` INT NOT NULL,
  `hipertenso` INT NULL,
  `diabetico` INT NULL,
  PRIMARY KEY (`cod_cliente`),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_cliente_estado_idx` (`cod_estado` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_estado`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `dfin`.`estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfin`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfin`.`produto` (
  `cod_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NULL,
  `cod_classe_produto` INT NULL,
  `classe_produto` VARCHAR(100) NULL,
  `valor` DECIMAL(10,2) NULL,
  PRIMARY KEY (`cod_produto`),
  UNIQUE INDEX `cod_produto_UNIQUE` (`cod_produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dfin`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dfin`.`compra` (
  `qtd_produto` INT NULL,
  `valor_unitario` DECIMAL(10,2) NULL,
  `valor_total_compra` DECIMAL(10,2) NULL,
  `cod_cliente` INT NOT NULL,
  `cod_produto` INT NOT NULL,
  INDEX `fk_compra_cliente1_idx` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_compra_produto1_idx` (`cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_compra_cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `dfin`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `dfin`.`produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
