-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 10:44:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tp2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tp2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tp2` DEFAULT CHARACTER SET utf8 ;
USE `tp2` ;

-- -----------------------------------------------------
-- Table `tp2`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp2`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`cod_pessoa`),
  UNIQUE INDEX `cod_pessoa_UNIQUE` (`cod_pessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp2`.`animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp2`.`animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL AUTO_INCREMENT,
  `animal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_animal_estimacao`),
  UNIQUE INDEX `animal_UNIQUE` (`animal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp2`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp2`.`bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_bebida`),
  UNIQUE INDEX `bebida_UNIQUE` (`bebida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp2`.`clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp2`.`clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `clima` VARCHAR(45) NULL,
  UNIQUE INDEX `clima_UNIQUE` (`clima` ASC) VISIBLE,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp2`.`hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp2`.`hobbie` (
  `cod_hobbie` INT NOT NULL AUTO_INCREMENT,
  `hobbie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hobbie`),
  UNIQUE INDEX `hobbie_UNIQUE` (`hobbie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tp2`.`pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp2`.`pesquisa` (
  `cod_pesquisa` INT NULL AUTO_INCREMENT,
  `data_pesquisa` DATE NOT NULL,
  `cod_hobbie` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_pessoa` INT NOT NULL,
  INDEX `fk_pesquisa_hobbie1_idx` (`cod_hobbie` ASC) VISIBLE,
  INDEX `fk_pesquisa_clima1_idx` (`cod_clima` ASC) VISIBLE,
  INDEX `fk_pesquisa_bebida1_idx` (`cod_bebida` ASC) VISIBLE,
  INDEX `fk_pesquisa_animal_estimacao1_idx` (`cod_animal_estimacao` ASC) VISIBLE,
  INDEX `fk_pesquisa_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  PRIMARY KEY (`cod_pesquisa`),
  CONSTRAINT `fk_pesquisa_hobbie1`
    FOREIGN KEY (`cod_hobbie`)
    REFERENCES `tp2`.`hobbie` (`cod_hobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `tp2`.`clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `tp2`.`bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_animal_estimacao1`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `tp2`.`animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `tp2`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
